language: node_js
node_js:
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
cache:
  directories:
    - "node_modules"
install:
  - npm install
  - npm run compile
  - npm install -g jest
before_script:
  - npm prune --production
  - mkdir gh-pages
  - npm run doc.github
  - npm run doc.shopify
  - npm run doc.starwars-js
  - npm run doc.starwars